### ISSUE TITLE
[Monterey] Messages sent as replies with subject line text and a space in the main body appear to not deliver/disappear

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/bluebubbles-helper#19]

**Comment by CSab6482** [comment]
This bug affects all subject line messages with no main body text, but the bug is more easily reproduceable when the message is sent as a reply

**Comment by tneotia** [comment]
This does not appear to happen on Ventura, gonna chalk this up to just some weird behavior with Monterey.

**Comment by CSab6482** [comment]
Request to reopen since I am still seeing this bug on Ventura

**Comment by tneotia** [comment]
fixed
