### ISSUE TITLE
[Feature request] Show other user's focus mode status

### ISSUE THREAD

**Issue by UvixCreative** [BlueBubblesApp/bluebubbles-helper#27]
This is distinct from #21, this is a feature request for the app to display other user's focus mode status. For example, a chat on the native app(s) will show "[User] has notifications silenced" due to their focus mode settings. When you send a message while the other user has notifications silenced as such, the status for the message shows as "Delivered quietly." It would be nice to have this functionality in BlueBubbles as well.

The native feature also has a button to "send a notification," overriding the default behavior of delivering the notification quietly. This would be a nice feature as well, but I'm personally not too concerned about it (and it might be worthy of a separate issue/request for itself)

**Comment by tneotia** [comment]
This is fully completed now
