### ISSUE TITLE
Private API (v0.0.14) Crashes iMessage Whenever it is Used

### ISSUE THREAD

**Issue by kurtwickboldt** [BlueBubblesApp/bluebubbles-helper#31]
Mid 2009 MBP - El Capitan 10.11.6
BlueBubbles Server v1.5.5
mySIMBL v0.8.1 (72)
BlueBubbles-Helper v0.0.14

iMessage quits unexpectedly whenever a private API feature is used.

iMessage Error:
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[IMChat sendMessageAcknowledgment:forChatItem:withMessageSummaryInfo:]: unrecognized selector sent to instance 0x7fce2bcd48d0'
terminating with uncaught exception of type NSException
abort() called

[iMessage Crash.txt](https://github.com/BlueBubblesApp/bluebubbles-helper/files/11091018/iMessage.Crash.txt)

![Screen Shot 2023-03-28 at 9 59 36 AM](https://user-images.githubusercontent.com/102988141/228282084-d28117d6-56c4-4bf9-b00e-2329afbc81c4.png)

Private API installed successfully through mySIMBL and restarted the BlueBubbles Server, but other helper versions don't work as well (0.0.11, 0.0.10, etc.) Log doesn't show any issues aside from the private helper API disconnecting (Whenever a message or reaction is sent)
![Screen Shot 2023-03-28 at 10 00 16 AM](https://user-images.githubusercontent.com/102988141/228282344-58d159e3-9310-4a2d-bec2-94eb9a0ad7bf.png)

mySIMBL Configuration:
![Screen Shot 2023-03-28 at 10 03 49 AM](https://user-images.githubusercontent.com/102988141/228282599-fe00b0c0-273a-4250-8445-decff35d21b4.png)

I appreciate any help with this!

**Comment by tneotia** [comment]
Hi there, we don't really support El Capitan on the private API. The lowest known working version of macOS is 10.12. Plus there aren't really any features to take advantage of on El Capitan regarding the private API (pretty sure only typing indicators exist, and I could be wrong about even that) so we haven't focused on getting compatibility.

**Comment by kurtwickboldt** [comment]
Upgrading from El Capitan to High Sierra solved this issue. Used the guide from http://dosdude1.com/highsierra/ to upgrade an "obsolete" 2009 MBP
