### ISSUE TITLE
[Feature Request] Download attachment to disk when it's stored in iCloud

### ISSUE THREAD

**Issue by jonluca** [BlueBubblesApp/bluebubbles-helper#32]
<img width="702" alt="img" src="https://user-images.githubusercontent.com/13029040/230743332-41ad00bf-f42b-4f87-8af1-5ef28c51e154.png">

A lot of really old messages with attachments will have the attachments in iCloud/stored remotely, which can be manually downloaded using the download icon in iMessages.

Would be interesting to figure which private API is used to download it (Maybe something in `IMFileTransferCenter`?)

**Comment by jonluca** [comment]
<img width="302" alt="capture 2023-04-10 at 3 30 11 PM" src="https://user-images.githubusercontent.com/13029040/231011247-fa13b25c-2415-46a3-9a6d-ef8bec850527.png">

One option thats kind of interesting is the "Disable iMessages in iCloud" - it will download all your historical attachments to your machine. There must be some kind of API to do this.

**Comment by tneotia** [comment]
done
