### ISSUE TITLE
Would it be possible to make it so that deleting messages on the android app, it deletes them on the host mac?

### ISSUE THREAD

**Issue by Debtless0805** [BlueBubblesApp/bluebubbles-helper#33]

**Comment by CompuGenius** [comment]
+1

**Comment by Debtless0805** [comment]
> requires private api

I have the private api set up. how would i be able to code this myself if nobody else is able. is there already an api i can invoke to find the specific message and delete it?

**Comment by CompuGenius** [comment]
I too am more than able to contribute, I'm just new to the BlueBubbles scene so will need to look around and figure out how all this works.

**Comment by Debtless0805** [comment]
wonderful. thanks a lot!

**Comment by iT3g4n** [comment]
This is a useful feature that I would like to use. If anyone else is unable to do it, how could i do it myself?

**Comment by tneotia** [comment]
done
