### ISSUE TITLE
[Feature Request] Mentions

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/bluebubbles-helper#5]
Here is a video showcasing the feature on iOS

https://user-images.githubusercontent.com/53708281/137012530-b9562918-a1fa-48ae-8648-da7faa3b5c00.mp4

and [here](https://youtu.be/19f4yo0sEFM?t=195) it is on macOS.
As seen in https://github.com/BlueBubblesApp/BlueBubbles-Desktop-App/issues/224, MyMessage has partial support for this feature since it shows mentioned names in boldface.

**Comment by tneotia** [comment]
Completed by @elliotnash because he's just that good
