### ISSUE TITLE
[Feature Request] Sync pinned chats from the Mac to the client apps

### ISSUE THREAD

**Issue by sabogalc** [BlueBubblesApp/bluebubbles-helper#6]
This would be a nice continuity feature, though it may cause issues for chats that were manually pinned on the Android app. Would those chats sync to the Mac and then be pinned there too? Let me know what you guys think.

**Comment by tneotia** [comment]
Implemented bundle side (pass in the chat guid and it will pin if it is unpinned in imessage or unpin if it is pinned in imessage). Please create a ticket on the client repo to support pulling from server and also updating the server side.
