### ISSUE TITLE
[Feature Request] Sync group chat images between the server and client

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/bluebubbles-helper#7]
[SMServer](https://github.com/iandwelker/smserver/blob/f3a8de59bdc27aded67f2fb4aeb5868953fa664c/src/SMServer/shared/ChatDelegate.swift#L565-L580), [WebMessage](https://github.com/sgtaziz/WebMessage-Tweak/blob/main/WebMessage/WebMessageServer.swift#L525-#L549), and MyMessage all support this feature. (Idk where the code is in MyMessage's library)

**Comment by tneotia** [comment]
This will be done via server pulling data from the chat.db
