### ISSUE TITLE
[Feature Request] Reacting to individual parts of a message with multiple parts

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/bluebubbles-helper#8]
https://github.com/BlueBubblesApp/bluebubbles-app/issues/542
https://github.com/BlueBubblesApp/BlueBubbles-Desktop-App/issues/196
https://github.com/iandwelker/smserver/issues/81
https://github.com/sgtaziz/WebMessage/issues/51
https://github.com/open-imcore/imcore.react/issues/8
https://github.com/airmessage/airmessage-android/issues/3

**Comment by tneotia** [comment]
Completed

**Comment by CSab6482** [comment]
![image0](https://user-images.githubusercontent.com/53708281/194112352-02920129-433e-4ef4-a0f4-3988a7f79d6a.gif)
